/**
 * Note 1: This module is the shared budgeting engine for the `/sankey` page.
 * Keeping the math and normalization logic in `lib/` lets the UI, persistence
 * routes, and tests all agree on how expenses, leftover savings, and grouped
 * Sankey branches should be derived from the same source data.
 */
import {
  BudgetAllocationEntry,
  BudgetExpense,
  CategoryType,
  SankeyData,
  SankeyLink,
  SankeyNode,
  SavedBudget,
} from "./types";

export const CATEGORY_ORDER: CategoryType[] = ["Need", "Want", "Saving"];

export const CATEGORY_LABELS: Record<CategoryType, string> = {
  Need: "Needs",
  Want: "Wants",
  Saving: "Savings",
};

export const CATEGORY_COLORS: Record<CategoryType, string> = {
  Need: "#ef4444",
  Want: "#38bdf8",
  Saving: "#22c55e",
};

const GROUP_COLORS: Record<CategoryType, string> = {
  Need: "#fb7185",
  Want: "#60a5fa",
  Saving: "#4ade80",
};

const CATEGORY_SHADE_PALETTES: Record<CategoryType, string[]> = {
  Need: ["#fca5a5", "#fda4af", "#fecaca", "#fb7185"],
  Want: ["#7dd3fc", "#93c5fd", "#bfdbfe", "#60a5fa"],
  Saving: ["#86efac", "#6ee7b7", "#bbf7d0", "#4ade80"],
};

const LEFTOVER_SAVINGS_COLOR = "#4ade80";
const NET_INCOME_COLOR = "#22d3ee";

type BudgetExpenseInput = Partial<BudgetExpense>;

export interface BudgetDraft {
  budgetId?: string;
  name: string;
  monthlyIncome: number;
  expenses: BudgetExpense[];
  createdAt?: string;
  updatedAt?: string;
}

export interface BudgetPieSlice {
  key: string;
  name: string;
  value: number;
  color: string;
  category: CategoryType;
  group?: string;
  autoGenerated?: boolean;
}

export interface BudgetInsights {
  monthlyIncome: number;
  totalExpenses: number;
  leftoverSavings: number;
  overspending: number;
  categoryTotals: Record<CategoryType, number>;
  pieData: BudgetPieSlice[];
  sankeyData: SankeyData;
  validExpenses: BudgetExpense[];
}

function roundCurrency(value: number): number {
  return Math.round((Number.isFinite(value) ? value : 0) * 100) / 100;
}

function normalizePositiveAmount(value: number): number {
  return value > 0 ? roundCurrency(value) : 0;
}

function trimText(value?: string): string {
  return (value ?? "").trim();
}

function createLocalId(prefix: string): string {
  if (
    typeof crypto !== "undefined" &&
    typeof crypto.randomUUID === "function"
  ) {
    return crypto.randomUUID();
  }

  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
}

function slugify(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "item"
  );
}

function getExpensePaletteColor(category: CategoryType, index: number): string {
  const palette = CATEGORY_SHADE_PALETTES[category];
  return palette[index % palette.length];
}

function getCategoryNodeId(category: CategoryType): string {
  return `category:${category}`;
}

function getGroupNodeId(category: CategoryType, group: string): string {
  return `group:${category}:${slugify(group)}`;
}

function inferLegacyCategoryType(label: string): CategoryType {
  const normalized = label.trim().toLowerCase();

  if (normalized.includes("saving") || normalized.includes("save")) {
    return "Saving";
  }

  if (
    normalized.includes("want") ||
    normalized.includes("fun") ||
    normalized.includes("discretion")
  ) {
    return "Want";
  }

  return "Need";
}

function normalizeBudgetExpenses(
  expenses: BudgetExpenseInput[],
  { fallbackNames }: { fallbackNames: boolean },
): BudgetExpense[] {
  let fallbackIndex = 1;
  const normalizedExpenses: BudgetExpense[] = [];

  for (const expense of expenses) {
    const amount = normalizePositiveAmount(Number(expense.amount));
    const category = expense.category ?? "Need";
    if (amount <= 0) {
      continue;
    }

    const trimmedName = trimText(expense.name);
    if (!trimmedName && !fallbackNames) {
      continue;
    }

    // Note 2: Preview charts need a stable label even while the user is halfway
    // through filling the form. Fallback names keep the visuals usable without
    // silently persisting unnamed expenses when the user saves.
    const name = trimmedName || `Expense ${fallbackIndex++}`;

    normalizedExpenses.push({
      expenseId: trimText(expense.expenseId) || createLocalId("expense"),
      name,
      amount,
      category,
      group: trimText(expense.group),
    });
  }

  return normalizedExpenses;
}

function normalizeLegacyAllocations(
  allocations: BudgetAllocationEntry[],
): BudgetExpense[] {
  return allocations.map((allocation) =>
    createBudgetExpense({
      name: allocation.category,
      amount: allocation.amount,
      category: inferLegacyCategoryType(allocation.category),
    }),
  );
}

function buildPieData(
  expenses: BudgetExpense[],
  leftoverSavings: number,
): BudgetPieSlice[] {
  const counters: Record<CategoryType, number> = {
    Need: 0,
    Want: 0,
    Saving: 0,
  };

  const slices: BudgetPieSlice[] = expenses.map((expense) => {
    const color = getExpensePaletteColor(
      expense.category,
      counters[expense.category],
    );
    counters[expense.category] += 1;

    return {
      key: expense.expenseId,
      name: expense.name,
      value: expense.amount,
      color,
      category: expense.category,
      group: trimText(expense.group),
    } satisfies BudgetPieSlice;
  });

  if (leftoverSavings > 0) {
    slices.push({
      key: "leftover-savings",
      name: "Leftover Savings",
      value: leftoverSavings,
      color: LEFTOVER_SAVINGS_COLOR,
      category: "Saving",
      autoGenerated: true,
    });
  }

  return slices;
}

function buildSankeyData(
  expenses: BudgetExpense[],
  leftoverSavings: number,
  colorByExpenseId: Map<string, string>,
): SankeyData {
  const nodes: SankeyNode[] = [];
  const links: SankeyLink[] = [];
  const seenNodes = new Set<string>();

  const pushNode = (node: SankeyNode) => {
    if (seenNodes.has(node.id)) {
      return;
    }

    seenNodes.add(node.id);
    nodes.push(node);
  };

  const categoryTotals: Record<CategoryType, number> = {
    Need: 0,
    Want: 0,
    Saving: leftoverSavings,
  };

  for (const expense of expenses) {
    categoryTotals[expense.category] = roundCurrency(
      categoryTotals[expense.category] + expense.amount,
    );
  }

  pushNode({
    id: "income",
    label: "Net Income",
    color: NET_INCOME_COLOR,
    kind: "income",
  });

  for (const category of CATEGORY_ORDER) {
    if (categoryTotals[category] <= 0) {
      continue;
    }

    pushNode({
      id: getCategoryNodeId(category),
      label: CATEGORY_LABELS[category],
      color: CATEGORY_COLORS[category],
      kind: "category",
      category,
    });

    links.push({
      source: "income",
      target: getCategoryNodeId(category),
      value: categoryTotals[category],
      startColor: NET_INCOME_COLOR,
      endColor: CATEGORY_COLORS[category],
      kind: "income-category",
    });
  }

  const groupTotals = new Map<
    string,
    { category: CategoryType; label: string; total: number }
  >();

  for (const expense of expenses) {
    const group = trimText(expense.group);
    if (!group || group.toLowerCase() === expense.name.toLowerCase()) {
      continue;
    }

    const groupId = getGroupNodeId(expense.category, group);
    const current = groupTotals.get(groupId) ?? {
      category: expense.category,
      label: group,
      total: 0,
    };

    current.total = roundCurrency(current.total + expense.amount);
    groupTotals.set(groupId, current);
  }

  for (const [groupId, metadata] of groupTotals) {
    pushNode({
      id: groupId,
      label: metadata.label,
      color: GROUP_COLORS[metadata.category],
      kind: "group",
      category: metadata.category,
    });

    links.push({
      source: getCategoryNodeId(metadata.category),
      target: groupId,
      value: metadata.total,
      startColor: CATEGORY_COLORS[metadata.category],
      endColor: GROUP_COLORS[metadata.category],
      kind: "category-group",
    });
  }

  for (const expense of expenses) {
    const expenseColor =
      colorByExpenseId.get(expense.expenseId) ??
      CATEGORY_COLORS[expense.category];
    const group = trimText(expense.group);
    const usesGroup =
      Boolean(group) && group.toLowerCase() !== expense.name.toLowerCase();

    pushNode({
      id: `expense:${expense.expenseId}`,
      label: expense.name,
      color: expenseColor,
      kind: "expense",
      category: expense.category,
    });

    links.push({
      source: usesGroup
        ? getGroupNodeId(expense.category, group)
        : getCategoryNodeId(expense.category),
      target: `expense:${expense.expenseId}`,
      value: expense.amount,
      startColor: usesGroup
        ? GROUP_COLORS[expense.category]
        : CATEGORY_COLORS[expense.category],
      endColor: expenseColor,
      kind: usesGroup ? "group-expense" : "category-expense",
    });
  }

  if (leftoverSavings > 0) {
    pushNode({
      id: "balance:leftover-savings",
      label: "Leftover Savings",
      color: LEFTOVER_SAVINGS_COLOR,
      kind: "balance",
      category: "Saving",
    });

    links.push({
      source: getCategoryNodeId("Saving"),
      target: "balance:leftover-savings",
      value: leftoverSavings,
      startColor: CATEGORY_COLORS.Saving,
      endColor: LEFTOVER_SAVINGS_COLOR,
      kind: "category-balance",
    });
  }

  return { nodes, links };
}

export function createBudgetExpense(
  overrides: Partial<BudgetExpense> = {},
): BudgetExpense {
  return {
    expenseId: trimText(overrides.expenseId) || createLocalId("expense"),
    name: overrides.name ?? "",
    amount: overrides.amount ?? 0,
    category: overrides.category ?? "Need",
    group: overrides.group ?? "",
  };
}

export function createDefaultBudgetDraft(): BudgetDraft {
  return {
    name: "",
    monthlyIncome: 5000,
    expenses: [createBudgetExpense()],
  };
}

export function hasBudgetRowContent(expense: BudgetExpense): boolean {
  return (
    trimText(expense.name).length > 0 ||
    normalizePositiveAmount(Number(expense.amount)) > 0 ||
    trimText(expense.group).length > 0
  );
}

export function normalizeBudgetForEditor(
  budget?: Partial<SavedBudget> | null,
): BudgetDraft {
  if (!budget) {
    return createDefaultBudgetDraft();
  }

  const expenses = budget.expenses?.length
    ? budget.expenses.map((expense) =>
        createBudgetExpense({
          ...expense,
          name: trimText(expense.name),
          amount: normalizePositiveAmount(Number(expense.amount)),
          group: trimText(expense.group),
        }),
      )
    : normalizeLegacyAllocations(budget.allocations ?? []);

  const totalExpenses = roundCurrency(
    expenses.reduce((sum, expense) => sum + expense.amount, 0),
  );

  return {
    budgetId: budget.budgetId,
    name: budget.name ?? "",
    monthlyIncome:
      typeof budget.monthlyIncome === "number" && budget.monthlyIncome > 0
        ? roundCurrency(budget.monthlyIncome)
        : totalExpenses,
    expenses: expenses.length ? expenses : [createBudgetExpense()],
    createdAt: budget.createdAt,
    updatedAt: budget.updatedAt,
  };
}

export function normalizeBudgetForStorage(
  budget: Omit<Partial<BudgetDraft>, "expenses"> & {
    expenses?: BudgetExpenseInput[];
  },
): SavedBudget {
  const expenses = normalizeBudgetExpenses(budget.expenses ?? [], {
    fallbackNames: false,
  });
  const totalExpenses = roundCurrency(
    expenses.reduce((sum, expense) => sum + expense.amount, 0),
  );

  return {
    budgetId: budget.budgetId,
    name: trimText(budget.name) || "Untitled budget",
    monthlyIncome:
      normalizePositiveAmount(Number(budget.monthlyIncome ?? 0)) ||
      totalExpenses,
    expenses,
    // Note 3: The legacy `allocations` field is still written so older callers
    // can keep reading the simplified `{ category, amount }` shape while the UI
    // now relies on the richer `expenses` array for grouping and category types.
    allocations: expenses.map((expense) => ({
      category: expense.name,
      amount: expense.amount,
    })),
    createdAt: budget.createdAt,
    updatedAt: budget.updatedAt,
  };
}

function getBudgetTimestamp(budget: Partial<SavedBudget>): number {
  const rawTimestamp = budget.updatedAt ?? budget.createdAt;
  if (!rawTimestamp) {
    return 0;
  }

  const parsed = Date.parse(rawTimestamp);
  return Number.isNaN(parsed) ? 0 : parsed;
}

/**
 * Note 4: Saved budgets are surfaced to users as "recent work", so the list and
 * the initial page load both sort by the freshest write timestamp first. Keeping
 * the comparison in one helper avoids subtle drift between the list order and
 * whichever item the page auto-selects on first render.
 */
export function sortSavedBudgets<T extends Partial<SavedBudget>>(
  budgets: T[],
): T[] {
  return [...budgets].sort((left, right) => {
    const recencyDelta = getBudgetTimestamp(right) - getBudgetTimestamp(left);

    if (recencyDelta !== 0) {
      return recencyDelta;
    }

    return (left.name ?? "").localeCompare(right.name ?? "");
  });
}

export function buildBudgetInsights(
  draft: Pick<BudgetDraft, "monthlyIncome" | "expenses">,
): BudgetInsights {
  const monthlyIncome = normalizePositiveAmount(Number(draft.monthlyIncome));
  const validExpenses = normalizeBudgetExpenses(draft.expenses, {
    fallbackNames: true,
  });
  const totalExpenses = roundCurrency(
    validExpenses.reduce((sum, expense) => sum + expense.amount, 0),
  );
  const leftoverSavings = roundCurrency(
    Math.max(monthlyIncome - totalExpenses, 0),
  );
  const overspending = roundCurrency(
    Math.max(totalExpenses - monthlyIncome, 0),
  );

  const categoryTotals: Record<CategoryType, number> = {
    Need: 0,
    Want: 0,
    Saving: leftoverSavings,
  };

  for (const expense of validExpenses) {
    categoryTotals[expense.category] = roundCurrency(
      categoryTotals[expense.category] + expense.amount,
    );
  }

  const pieData = buildPieData(validExpenses, leftoverSavings);
  const colorByExpenseId = new Map(
    pieData
      .filter((slice) => !slice.autoGenerated)
      .map((slice) => [slice.key, slice.color]),
  );

  return {
    monthlyIncome,
    totalExpenses,
    leftoverSavings,
    overspending,
    categoryTotals,
    pieData,
    sankeyData: buildSankeyData(
      validExpenses,
      leftoverSavings,
      colorByExpenseId,
    ),
    validExpenses,
  };
}
