/**
 * Note 1: Sankey diagram and pie chart data construction for budget visualization.
 * Transforms normalized BudgetExpense arrays into the node/link graph structures
 * consumed by the Sankey renderer and the pie chart.
 *
 * Dependency chain: sankey-builder → budget-normalizer (parseSankeyPathSegments)
 * No dependency on budget-calculator, so this module is safe to import from
 * both the calculator layer and directly from UI components.
 *
 * Color strategy:
 *  - Category nodes use fixed semantic colors (CATEGORY_COLORS).
 *  - Per-expense nodes use a shaded palette derived from their category.
 *  - Path/branch nodes use a hash of their root label to pick from
 *    PATH_ROOT_COLORS, then lighten with depth so nested nodes stay distinct.
 */
import {
  BudgetExpense,
  CategoryType,
  SankeyData,
  SankeyLink,
  SankeyNode,
} from "../types/types";
import { parseSankeyPathSegments } from "./budget-normalizer";

// ---------------------------------------------------------------------------
// Exported color constants (also consumed by UI components for legends/badges)
// ---------------------------------------------------------------------------

export const CATEGORY_COLORS: Record<CategoryType, string> = {
  Need: "#ef4444",
  Want: "#38bdf8",
  Saving: "#22c55e",
};

// ---------------------------------------------------------------------------
// Private color palettes and constants
// ---------------------------------------------------------------------------

const CATEGORY_SHADE_PALETTES: Record<CategoryType, string[]> = {
  Need: ["#fca5a5", "#fda4af", "#fecaca", "#fb7185"],
  Want: ["#7dd3fc", "#93c5fd", "#bfdbfe", "#60a5fa"],
  Saving: ["#86efac", "#6ee7b7", "#bbf7d0", "#4ade80"],
};

// Note 2: Root-branch colors are assigned deterministically via hashString so
// the same path always renders in the same hue across page reloads and across
// different budget snapshots.
const PATH_ROOT_COLORS = [
  "#38bdf8",
  "#818cf8",
  "#f59e0b",
  "#f472b6",
  "#34d399",
  "#fb7185",
  "#22d3ee",
  "#a78bfa",
];
const LEFTOVER_SAVINGS_COLOR = "#4ade80";
const NET_INCOME_COLOR = "#22d3ee";

// ---------------------------------------------------------------------------
// Exported type
// ---------------------------------------------------------------------------

/** A single slice of the budget pie chart, derived from a BudgetExpense. */
export interface BudgetPieSlice {
  key: string;
  name: string;
  value: number;
  color: string;
  category: CategoryType;
  group?: string;
  /** True for the synthetic "Leftover Savings" slice; absent on real expenses. */
  autoGenerated?: boolean;
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

function trimText(value?: string): string {
  return (value ?? "").trim();
}

function roundCurrency(value: number): number {
  return Math.round((Number.isFinite(value) ? value : 0) * 100) / 100;
}

// Note 3: slugify converts human-readable path labels into stable, URL-safe
// node IDs. The same label must always produce the same slug so that
// pushNode's deduplication set correctly merges branches shared across
// multiple expenses (e.g. two "Housing > *" items share one path node).
function slugify(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "item"
  );
}

function getExpensePaletteColor(category: CategoryType, index: number): string {
  const palette = CATEGORY_SHADE_PALETTES[category];
  return palette[index % palette.length];
}

function hashString(value: string): number {
  let hash = 0;

  for (let index = 0; index < value.length; index += 1) {
    hash = (hash * 31 + value.charCodeAt(index)) >>> 0;
  }

  return hash;
}

/**
 * Mix two hex colors by `weight` (0 = fully left, 1 = fully right).
 * Used to lighten branch nodes with each level of nesting depth.
 */
function mixHexColors(left: string, right: string, weight: number): string {
  const normalizedWeight = Math.min(Math.max(weight, 0), 1);
  const leftHex = left.replace("#", "");
  const rightHex = right.replace("#", "");

  const mixed = [0, 2, 4]
    .map((offset) => {
      const leftChannel = parseInt(leftHex.slice(offset, offset + 2), 16);
      const rightChannel = parseInt(rightHex.slice(offset, offset + 2), 16);
      const channel = Math.round(
        leftChannel + (rightChannel - leftChannel) * normalizedWeight,
      );

      return channel.toString(16).padStart(2, "0");
    })
    .join("");

  return `#${mixed}`;
}

function getPathNodeId(pathSegments: string[]): string {
  return `path:${pathSegments.map(slugify).join("/")}`;
}

function getPathNodeColor(pathSegments: string[]): string {
  const rootSegment = pathSegments[0] ?? "branch";
  const baseColor =
    PATH_ROOT_COLORS[hashString(rootSegment) % PATH_ROOT_COLORS.length];

  // Lighten the color slightly with each additional depth level so nested
  // branches remain visually distinct without needing a separate palette.
  return mixHexColors(
    baseColor,
    "#ffffff",
    Math.min(Math.max(pathSegments.length - 1, 0) * 0.16, 0.45),
  );
}

// ---------------------------------------------------------------------------
// Exported builders
// ---------------------------------------------------------------------------

/**
 * Build the pie chart slice array from a validated list of expenses.
 * A synthetic "Leftover Savings" slice is appended when income exceeds spend.
 */
export function buildPieData(
  expenses: BudgetExpense[],
  leftoverSavings: number,
): BudgetPieSlice[] {
  const counters: Record<CategoryType, number> = {
    Need: 0,
    Want: 0,
    Saving: 0,
  };

  const slices: BudgetPieSlice[] = expenses.map((expense) => {
    const color = getExpensePaletteColor(
      expense.category,
      counters[expense.category],
    );
    counters[expense.category] += 1;

    return {
      key: expense.expenseId,
      name: expense.name,
      value: expense.amount,
      color,
      category: expense.category,
      group: trimText(expense.group),
    } satisfies BudgetPieSlice;
  });

  if (leftoverSavings > 0) {
    slices.push({
      key: "leftover-savings",
      name: "Leftover Savings",
      value: leftoverSavings,
      color: LEFTOVER_SAVINGS_COLOR,
      category: "Saving",
      autoGenerated: true,
    });
  }

  return slices;
}

/**
 * Build the Sankey node/link graph from validated expenses.
 *
 * Note 4: Links between the same source→target pair are merged (values summed)
 * so that multiple expenses sharing a path branch contribute to a single,
 * correctly-sized flow band rather than rendering as parallel duplicate links.
 *
 * @param colorByExpenseId - Map from expenseId to pre-computed pie slice color
 *   so that expense nodes match their corresponding pie wedge exactly.
 */
export function buildSankeyData(
  expenses: BudgetExpense[],
  leftoverSavings: number,
  colorByExpenseId: Map<string, string>,
): SankeyData {
  const nodes: SankeyNode[] = [];
  const links = new Map<string, SankeyLink>();
  const seenNodes = new Set<string>();

  const pushNode = (node: SankeyNode) => {
    if (seenNodes.has(node.id)) {
      return;
    }

    seenNodes.add(node.id);
    nodes.push(node);
  };

  const pushLink = (link: SankeyLink) => {
    const key = `${link.source}->${link.target}`;
    const current = links.get(key);

    if (current) {
      current.value = roundCurrency(current.value + link.value);
      return;
    }

    links.set(key, { ...link });
  };

  pushNode({
    id: "income",
    label: "Gross",
    color: NET_INCOME_COLOR,
    kind: "income",
  });

  for (const expense of expenses) {
    const expenseColor =
      colorByExpenseId.get(expense.expenseId) ??
      CATEGORY_COLORS[expense.category];
    const pathSegments = parseSankeyPathSegments(expense.group, expense.name);
    let sourceId = "income";
    let sourceColor = NET_INCOME_COLOR;

    for (let index = 0; index < pathSegments.length; index += 1) {
      const currentPath = pathSegments.slice(0, index + 1);
      const pathId = getPathNodeId(currentPath);
      const pathColor = getPathNodeColor(currentPath);

      pushNode({
        id: pathId,
        label: currentPath[currentPath.length - 1],
        color: pathColor,
        kind: "path",
      });

      pushLink({
        source: sourceId,
        target: pathId,
        value: expense.amount,
        startColor: sourceColor,
        endColor: pathColor,
        kind: sourceId === "income" ? "income-path" : "path-path",
      });

      sourceId = pathId;
      sourceColor = pathColor;
    }

    pushNode({
      id: `expense:${expense.expenseId}`,
      label: expense.name,
      color: expenseColor,
      kind: "expense",
      category: expense.category,
    });

    pushLink({
      source: sourceId,
      target: `expense:${expense.expenseId}`,
      value: expense.amount,
      startColor: sourceColor,
      endColor: expenseColor,
      kind: pathSegments.length > 0 ? "path-expense" : "income-expense",
    });
  }

  if (leftoverSavings > 0) {
    pushNode({
      id: "balance:leftover-savings",
      label: "Leftover Savings",
      color: LEFTOVER_SAVINGS_COLOR,
      kind: "balance",
      category: "Saving",
    });

    pushLink({
      source: "income",
      target: "balance:leftover-savings",
      value: leftoverSavings,
      startColor: NET_INCOME_COLOR,
      endColor: LEFTOVER_SAVINGS_COLOR,
      kind: "income-balance",
    });
  }

  return { nodes, links: Array.from(links.values()) };
}
